package javaDeepDrive.enums;

/*
========================================================
1. SIMPLE ENUM (WITHOUT CUSTOM VALUE)
========================================================
*/

enum Level {

    LOW,
    MEDIUM,
    HIGH

}

/*
--------------------------------------------------------
INTERNAL STRUCTURE GENERATED BY COMPILER
--------------------------------------------------------

final class Level extends Enum<Level>{

    public static final Level LOW =
            new Level("LOW",0);

    public static final Level MEDIUM =
            new Level("MEDIUM",1);

    public static final Level HIGH =
            new Level("HIGH",2);


    private static final Level[] values = {
            LOW, MEDIUM, HIGH
    };

    private Level(String name,int ordinal){
        super(name,ordinal);
    }

    public static Level[] values(){
        return values.clone();
    }

    public static Level valueOf(String name){
        // internal implementation
    }
}

--------------------------------------------------------
MEMORY VIEW
--------------------------------------------------------

LOW object
    name = LOW
    ordinal = 0

MEDIUM object
    name = MEDIUM
    ordinal = 1

HIGH object
    name = HIGH
    ordinal = 2

--------------------------------------------------------
IMPORTANT POINTS
--------------------------------------------------------

1. Every enum constant is an OBJECT
2. Objects are static final
3. Constructor is private internally
4. values() method generated automatically
5. ordinal() gives index
6. name() gives constant name

*/



/*
========================================================
2. ENUM WITH CUSTOM VALUE
========================================================
*/

enum Status {

    SUCCESS(200),
    NOT_FOUND(404),
    SERVER_ERROR(500);

    private int code;

    Status(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}

/*
--------------------------------------------------------
INTERNAL STRUCTURE GENERATED BY COMPILER
--------------------------------------------------------

final class Status extends Enum<Status>{

    public static final Status SUCCESS =
            new Status("SUCCESS",0,200);

    public static final Status NOT_FOUND =
            new Status("NOT_FOUND",1,404);

    public static final Status SERVER_ERROR =
            new Status("SERVER_ERROR",2,500);


    private int code;


    private Status(String name,
                   int ordinal,
                   int code){

        super(name,ordinal);

        this.code = code;
    }


    public int getCode(){
        return code;
    }
}

--------------------------------------------------------
HOW VALUE PASSES
--------------------------------------------------------

SUCCESS(200)
    ↓
new Status(200)
    ↓
constructor called
    ↓
this.code = 200

--------------------------------------------------------
MEMORY VIEW
--------------------------------------------------------

SUCCESS object
    name = SUCCESS
    ordinal = 0
    code = 200

NOT_FOUND object
    name = NOT_FOUND
    ordinal = 1
    code = 404

SERVER_ERROR object
    name = SERVER_ERROR
    ordinal = 2
    code = 500

*/


public class EnumDeepDrive {

    public static void main(String[] args) {

        /*
        ================================================
        SIMPLE ENUM USAGE
        ================================================
        */

        Level level = Level.HIGH;

        System.out.println(level);

        System.out.println(level.ordinal());

        System.out.println(level.name());



        /*
        ================================================
        LOOPING ENUM
        ================================================
        */

        for(Level l : Level.values()){

            System.out.println(l);

        }



        /*
        ================================================
        ENUM WITH CUSTOM VALUE
        ================================================
        */

        Status status = Status.SUCCESS;

        System.out.println(status);

        System.out.println(status.getCode());



        /*
        ================================================
        == WORKS BECAUSE ENUM CONSTANTS
        ARE SINGLETON OBJECTS
        ================================================
        */

        Status s1 = Status.SUCCESS;
        Status s2 = Status.SUCCESS;

        System.out.println(s1 == s2);



        /*
        ================================================
        SWITCH WITH ENUM
        ================================================
        */

        switch(level){

            case LOW:
                System.out.println("Low Level");
                break;

            case MEDIUM:
                System.out.println("Medium Level");
                break;

            case HIGH:
                System.out.println("High Level");
                break;
        }
    }
}